export const CAREERS = [
  {
    position: 'Lead Frontend Engineer',
    company: 'Sirka.io',
    logo: '/images/careers/sirka.png',
    location: 'Jakarta',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-03',
    end_date: null,
    industry: 'wellness',
    link: 'https://sirka.io',
  },
  {
    position: 'Sr. Frontend Engineer',
    company: 'Sirka.io',
    logo: '/images/careers/sirka.png',
    location: 'Jakarta',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-12',
    end_date: '2022-03',
    industry: 'wellness',
    link: 'https://sirka.io',
  },
  {
    position: 'Founder',
    company: 'FlexCode',
    logo: '/images/careers/flexcode.png',
    location: 'Jakarta',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: null,
    industry: 'wellness',
    link: 'https://flexcode.co.id',
  },
  {
    position: 'Frontend Developer',
    company: 'Paper.id',
    logo: '/images/careers/paper-id.png',
    location: 'Jakarta',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2020-02',
    end_date: '2021-12',
    industry: 'financing',
    link: 'https://paper.id',
  },
  {
    position: 'Full-Stack Developer',
    company: 'Gama Plantation',
    logo: '/images/careers/kpn.png',
    location: 'Jakarta',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2019-09',
    end_date: '2020-02',
    industry: 'agriculture',
    link: 'https://www.linkedin.com/company/pt-gama-plantation',
  },
  {
    position: 'Full-Stack Developer',
    company: 'Rencong Network',
    logo: '/images/careers/rencong.png',
    location: 'Aceh',
    location_type: 'Onsite',
    type: 'Freelance',
    start_date: '2014-12',
    end_date: '20219-09',
    industry: 'software house',
    link: 'https://www.linkedin.com/company/rencongnetwork',
  },
]