import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Full Stack Engineer',
    company: 'Seeru',
    logo: '/images/careers/seeru.webp',
    location: 'Dubai, UAE',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2023-11',
    end_date: null,
    industry: 'ota',
    link: 'https://seeru.com',
  },
  {
    position: 'Lead Frontend Engineer',
    company: 'Sirka.io',
    logo: '/images/careers/sirka.png',
    location: 'Jakarta, ID',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2022-03',
    end_date: '2023-12',
    industry: 'wellness',
    link: 'https://sirka.io',
  },
  {
    position: 'Senior Frontend Engineer',
    company: 'Sirka.io',
    logo: '/images/careers/sirka.png',
    location: 'Jakarta, ID',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-12',
    end_date: '2022-03',
    industry: 'wellness',
    link: 'https://sirka.io',
  },
  {
    position: 'Co-Founder & CTO',
    company: 'FlexCode',
    logo: '/images/careers/flexcode.png',
    location: 'Jakarta, ID',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: null,
    industry: 'wellness',
    link: 'https://flexcode.co.id',
  },
  {
    position: 'Frontend Developer',
    company: 'Paper.id',
    logo: '/images/careers/paper-id.png',
    location: 'Jakarta, ID',
    location_type: 'Hybrid',
    type: 'Fulltime',
    start_date: '2020-02',
    end_date: '2021-12',
    industry: 'financing',
    link: 'https://paper.id',
  },
  {
    position: 'Full Stack Developer',
    company: 'Gama Plantation',
    logo: '/images/careers/kpn.png',
    location: 'Jakarta, ID',
    location_type: 'Onsite',
    type: 'Fulltime',
    start_date: '2019-09',
    end_date: '2020-02',
    industry: 'agriculture',
    link: 'https://www.linkedin.com/company/pt-gama-plantation',
  },
  {
    position: 'Full Stack Developer',
    company: 'Rencong Network',
    logo: '/images/careers/rencong.png',
    location: 'Aceh, ID',
    location_type: 'Onsite',
    type: 'Freelance',
    start_date: '2014-12',
    end_date: '2019-09',
    industry: 'software house',
    link: 'https://www.linkedin.com/company/rencongnetwork',
  },
  {
    position: 'Web Developer',
    company: 'PT. Kuala Nanggroe',
    logo: null,
    location: 'Aceh, ID',
    location_type: 'Onsite',
    type: 'Part-time',
    start_date: '2016-12',
    end_date: '2017-08',
    industry: 'travel',
    link: 'https://travelkuala.com',
  },
  {
    position: 'Web Developer',
    company: 'MA Ruhul Islam',
    logo: '/images/careers/riab.png',
    location: 'Aceh, ID',
    location_type: 'Onsite',
    type: 'Part-time',
    start_date: '2015-01',
    end_date: '2016-01',
    industry: 'school',
    link: 'https://ruhulislam.com',
  },
];
